% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Data 605 - Assignment 9},
  pdfauthor={Leticia Salazar},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{Data 605 - Assignment 9}
\author{Leticia Salazar}
\date{3/25/2022}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\hypertarget{central-limit-theorem-generating-functions}{%
\subsection{Central Limit Theorem \& Generating
Functions:}\label{central-limit-theorem-generating-functions}}

\hypertarget{exercise-11-page-363}{%
\subsubsection{1. Exercise 11 page 363}\label{exercise-11-page-363}}

The price of one share of stock in the Pilsdorff Beer Company (see
Exercise 8.2.12) is given by \(Y_n\) on the \_n\_th day of the year.
Finn observes that the differences \(X_n = Y_{n + 1} - Y_n\) appear to
be independent random variables with a common distribution having mean
\(\mu = 0\) and variance \(\sigma = 1 / 4\). If \(Y_1\) = 100, estimate
the probability that \(Y_365\) is:

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\item
  \(\ge 100\)
\item
  \(\ge 110\)
\item
  \(\ge 120\)
\end{enumerate}

\textbf{Solutions:}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# greater than or equal to 100}
\DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{pnorm}\NormalTok{((}\DecValTok{100} \SpecialCharTok{{-}} \DecValTok{100}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ (}\FloatTok{0.5} \SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(}\DecValTok{365} \SpecialCharTok{{-}} \DecValTok{1}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# greater than or equal to 110}
\DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{pnorm}\NormalTok{((}\DecValTok{110} \SpecialCharTok{{-}} \DecValTok{100}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ (}\FloatTok{0.5} \SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(}\DecValTok{365} \SpecialCharTok{{-}} \DecValTok{1}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1472537
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# greater than or equal to 120}
\DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{pnorm}\NormalTok{((}\DecValTok{120} \SpecialCharTok{{-}} \DecValTok{100}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ (}\FloatTok{0.5} \SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(}\DecValTok{365} \SpecialCharTok{{-}} \DecValTok{1}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.01801584
\end{verbatim}

Probability that \(Y_365\) for \(\ge 100\) is 0.5, for \(\ge 110\) it's
0.147 and for \(\ge 120\) it's 0.0180.

\hypertarget{calculate-the-expected-value-and-variance-of-the-binomial-distribution-using-the-moment-generating-function.}{%
\subsubsection{2. Calculate the expected value and variance of the
binomial distribution using the moment generating
function.}\label{calculate-the-expected-value-and-variance-of-the-binomial-distribution-using-the-moment-generating-function.}}

The moment generating function (MGF) is: \(M_z (t) = Expected(e^{tx})\)

The binomial probability mass function (PMF) is:
\(P_x = \binom{n}{x}p^x (1 - p)^{n - x}\)

The combination of MGF and PMF is:
\(M_z (t) = \sum_{x = 0}^{n} e^{tx} * \binom{n}{x}p^x (1 - p)^{n - x}\)

Simplified when t is a real number: M(t) = \((pe^t + 1 - p)^n\)

First instant of expected value: M'(t) = \(npe^t(pe^t - p + 1)^{n-1}\)

At 0 we get this expected value: M'(0) =
\(npe^0(pe^0 - p + 1)^{n-1} = np(p - p + 1)^{n - 1} = np(1)^{n - 1} = np\)

For the variance:

\(M^n(t) = npe^t(pe^t - p + 1)^{n-2}(npe^t -p +1)\)

\(M^n(0) = npe^0(pe^0 - p + 1)^{n-2}(npe^0 -p +1) = np(np - p + 1)\)

Therefore the expected binomial distribution is \emph{np} and the
variance is \emph{np(np - p + 1)}.

\hypertarget{calculate-the-expected-value-and-variance-of-the-exponential-distribution-using-the-moment-generating-function.}{%
\subsubsection{3. Calculate the expected value and variance of the
exponential distribution using the moment generating
function.}\label{calculate-the-expected-value-and-variance-of-the-exponential-distribution-using-the-moment-generating-function.}}

The exponential distribution: \(\lambda e^{-\lambda x}\) when x
\(\ge 0\)

\(M(t)=\int^\inf_0e^{tx}*\lambda e^{-\lambda x}=-\frac{\lambda}{t-\lambda}\)

The expected value evaluated at 0:
\(M'(t) = \dfrac{\lambda}{(t-\lambda)^2}\)

\(M'(0) = 1\)

\(M^n(t) = -\dfrac{2\lambda}{(t-\lambda)^3}\)

\(M^n(0) = -\dfrac{2\lambda}{(-\lambda)^3} = 2 / \lambda ^2\)

The expected value is \(1 / \lambda\) and the variance is
\(2 / \lambda ^2\)

\hypertarget{references}{%
\subsubsection{References:}\label{references}}

Some good explanation for MGF
\url{https://towardsdatascience.com/moment-generating-function-explained-27821a739035}

\end{document}
