---
title: "Data 605 Discussion Board"
author: "Leticia Salazar"
date: "3/2/2022"
output:
  html_document: 
    theme: journal
    highlight: pygments
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Probability

#### Exercise 1 Chapter 4

##### One of the first conditional probability paradoxes was provided by Bertrand. It is called the *Box Paradox*. A cabinet as three drawers. In the first drawer there are two golden balls, in the second drawer there are two silver balls, and in the third drawer there is one silver and one gold ball. A drawer is picked at random and a ball chosen at radom from the two balls in the drawer. Given that a gold ball was drawn, what is the probability that the drawer with the two gold balls was chosen?

$~$

#### Denotation:

##### $A_{i}$ where i = the number of drawer
##### G = the gold ball drawn
##### We are given that $A_{i}$ = 1/3

$~$

#### Finding the probabilities:

* Probability there are two gold balls in the first drawer and a gold ball is selected

P(G | $A_{1}$) = 2 / 2 = 1


* Probability there are no gold ball in the second drawer

P(G | $A_{2}$) = 0 / 2 = 0


* Probability there is one gold ball and one silver ball in the third drawer

P(G | $A_{3}$) = 1 / 2 = 0.5

$~$

#### Find probability that the drawer with the two gold balls was chosen or P($A_{1}$ | G)

$~$

##### Bayes' Theorem:

P(A | B) = $\frac{P(B | A) * P(A)}{P(B)}$

A, B	=	events

P(A|B)	=	probability of A given B is true

P(B|A)	=	probability of B given A is true

P(A), P(B)	=	the independent probabilities of A and B

$~$

##### Bayes' Theorem applied to our problem

**P($A_{1}$ | G) = $\frac{P(G | A_{1}) * P(A_{1})}{(P(G | A_{1}) * P(A_{1})) + (P(G | A_{2}) * P(G | A_{2})) + (P(G | A_{3}) * P(G | A_{3}))}$**


**P($A_{1}$ | G) = $\frac{(1 * \frac{1}{3})}{(1 * \frac{1}{3}) + (0 * \frac{1}{3}) + (\frac{1}{2} * \frac{1}{3})}$**

**P($A_{1}$ | G) = $\frac{2}{3}$**

$~$

#### Therefore:

##### There is a 66.67% probability that the drawer with the two gold balls was chosen

